"""
Optimization Engine Models.
Defines the structures for proposals generated by statistical analysis of the Event Chronicle.
"""
from enum import Enum
from pydantic import BaseModel, Field

class OptimizationCategory(str, Enum):
    EXECUTION_ORDER = "execution_order"
    STRATEGY_PREFERENCE = "strategy_preference"
    UNUSED_STEP = "unused_step"
    RETRY_OPTIMIZATION = "retry_optimization"
    WORKFLOW_SIMPLIFICATION = "workflow_simplification"

class OptimizationProposal(BaseModel):
    """A human-readable proposal for optimizing NOVA's deterministic behavior."""
    proposal_id: str = Field(..., description="Unique ID for this proposal (e.g., 'opt_workspace_startup')")
    category: OptimizationCategory
    affected_skill: str = Field(..., description="The Skill or Goal ID this optimization targets")
    reason: str = Field(..., description="The statistical evidence backing this proposal")
    confidence: float = Field(..., description="Statistical confidence (0.0 to 1.0)")
    expected_benefit: str = Field(..., description="Human-readable description of what will improve")
    risk: str = Field(default="Low", description="Potential downsides")
    requires_approval: bool = Field(default=True, description="Enforces Human Sovereignty (Law 3)")
