"""
NOVA SDK Project Generator.
Scaffolds new extensions (Skills, Capabilities, Providers).
"""
import os
import json
import logging

logger = logging.getLogger(__name__)

SKILL_TEMPLATE_PY = """
# Generated by NOVA SDK
class {class_name}Skill:
    def __init__(self):
        pass
        
    def get_workflow(self):
        return []
"""

MANIFEST_TEMPLATE = {
    "name": "{ext_name}",
    "version": "0.1.0",
    "type": "{ext_type}",
    "permissions": [],
    "dependencies": []
}

class ProjectGenerator:
    """Generates the file structure for a new NOVA extension."""
    
    def generate(self, ext_type: str, ext_name: str, output_dir: str = "."):
        """Creates a new extension project."""
        logger.info(f"Generating new {ext_type} '{ext_name}' in '{output_dir}'")
        
        project_dir = os.path.join(output_dir, ext_name)
        
        if os.path.exists(project_dir):
            raise FileExistsError(f"Directory {project_dir} already exists.")
            
        # Create directories
        os.makedirs(project_dir)
        os.makedirs(os.path.join(project_dir, "src"))
        os.makedirs(os.path.join(project_dir, "tests"))
        
        # Create manifest
        manifest = MANIFEST_TEMPLATE.copy()
        manifest["name"] = ext_name
        manifest["type"] = ext_type
        
        with open(os.path.join(project_dir, "manifest.json"), "w") as f:
            json.dump(manifest, f, indent=4)
            
        # Create python stub
        class_name = "".join([word.capitalize() for word in ext_name.split("_")])
        
        with open(os.path.join(project_dir, "src", "main.py"), "w") as f:
            f.write(SKILL_TEMPLATE_PY.replace("{class_name}", class_name))
            
        logger.info(f"Successfully generated {ext_type} '{ext_name}'.")
        return project_dir
